### ISSUE TITLE
Sensitive Information Exposure

### ISSUE THREAD

**Issue by hackelite01** [thetruthkenhurt/DeepPurple_Ken#1]
Hi @thetruthkenhurt ,

I noticed that the file `README.MD` in this repository contains sensitive information such as API keys and project IDs. Exposing these details in a public repository is not secure as it could lead to unauthorized access to your services and data.

**Suggested Action:**
- Remove the sensitive information from the `README.MD` file immediately.
- Use environment variables to manage sensitive information securely.
- Regenerate any exposed keys and update your environment configurations accordingly.

For more information on securely managing sensitive information, refer to the [GitHub documentation on secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets).

Thank you.

**Comment by thetruthkenhurt** [comment]
Thank you for your input. Upon review of the contents of the README, I have removed the contents of environment variables and advised users to setup their own .env file with the required variables. Note that no API keys have been exposed or revealed.

**Comment by hackelite01** [comment]
No issues. That's great you have changes that but simply changing the file content will not secure the repository, as the keys & IDs can still be found in the commit history. I suggest:

Make the repository private to secure it.
Alternatively, create a new repository with the same code base, ensuring that the sensitive information is not included in the commit history.
